### ISSUE TITLE
添加评论区 评论的功能

### ISSUE THREAD

**Issue by MewX** [MewX/light-novel-library_Wenku8_Android#35]
之前由于评论区的API除了问题，无法调通： #18 

短时间内无法修复，所以另开新的issue来处理。

- [x] 发新帖
- [x] 发表新的回复

**Comment by diais** [comment]
感谢大佬更新维护，另外能否麻烦您做一下分屏功能呢？

**Comment by MewX** [comment]
很多尝试，但是都不知道API到底是什么样，如果有大佬感兴趣的话可以破解一下。

```
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
4
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
4
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
4
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
Traceback (most recent call last):
  File "run.py", line 330, in <module>
    print(application())
  File "run.py", line 326, in application
    ReqReviewReplyEnglish = 'action=review&do=reply&rid=172444&content=' + base64.b64encode('testing english only').decode('utf-8')
  File "/usr/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=suLK1MbAwtvfwqOsN7j219azpLLiytTGwMLb38KjrDe49tfWs6Q=
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=dGVzdGluZyBlbmdsaXNoIG9ubHk=
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&content=asdfasdfasdfasdfasdfasdfadfassdaf
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&pcontent=asdfasdfasdfasdfasdfasdfadfassdaf
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&pcontent=testing+english+only+123
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&pcontent=asdfasdfasdfasdfasdfasdfadfassdafdGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
[mewx@mewx-manjaro wenku8testing]$ kkjkjj^C
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&pcontent=dGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&ptitle=&pcontent=dGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&ptitle=asdfadsf&pcontent=dGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&pcontent=dGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&pcontent=testing+english+only+123
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&pcontent=testing+english+only+123
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&ptitle=123412341234&pcontent=testing+english+only+123
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&title=123412341234&content=testing+english+only+123
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
  File "run.py", line 326
    ReqReviewReplyEnglish = 'action=review&do=reply&rid=172444&aid=1163&title='+base64.b64encode('123412341234''.encode('gb2312')).decode('utf-8')+&content='+base64.b64encode('testing+english+only+123''.encode('gb2312')).decode('utf-8')
                                                                                                                              ^
SyntaxError: invalid syntax
[mewx@mewx-manjaro wenku8testing]$ python run.py 
  File "run.py", line 326
    ReqReviewReplyEnglish = 'action=review&do=reply&rid=172444&aid=1163&title='+base64.b64encode('123412341234''.encode('gb2312')).decode('utf-8')+&content='+base64.b64encode('testing+english+only+123'.encode('gb2312')).decode('utf-8')
                                                                                                                              ^
SyntaxError: invalid syntax
[mewx@mewx-manjaro wenku8testing]$ python run.py 
  File "run.py", line 326
    ReqReviewReplyEnglish = 'action=review&do=reply&rid=172444&aid=1163&title='+base64.b64encode('123412341234'.encode('gb2312')).decode('utf-8')+&content='+base64.b64encode('testing+english+only+123'.encode('gb2312')).decode('utf-8')
                                                                                                                                                  ^
SyntaxError: invalid syntax
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&title=MTIzNDEyMzQxMjM0&content=dGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
[mewx@mewx-manjaro wenku8testing]$ python run.py 
action=review&do=reply&rid=172444&aid=1163&ptitle=MTIzNDEyMzQxMjM0&pcontent=dGVzdGluZytlbmdsaXNoK29ubHkrMTIz
11
```

**Comment by MewX** [comment]
Done
